#!/bin/bash
convert_dir=$1
output_dir=$2
bitrate=$3

# Ensure require params are passed in
if [ -z $convert_dir ] || [ -z $output_dir ];
then
  echo "Usage: flac2mp3 rip_dir output_dir [bitrate]"
  exit
fi

# Default to 320 kbps if bitrate not specified
if [ -z $bitrate ];
then
  bitrate=320
fi

# Get the list of files to convert
files=( `find $convert_dir -iname '*.flac' | tr "\n" " "` )

# Convert each file, one at a time
for file in ${files[*]}
do
  metaflac --export-tags-to=- "$file" | sed 's/=\(.*\)/="\1"/' | sed 's/\(.*\)/\L\1/' >tmp.tmp
  cat tmp.tmp
  . ./tmp.tmp
  rm tmp.tmp
  flac -dc $file | lame -b $bitrate -h --tt "$title" --tn "$tracknumber" --tg "$genre" --ty "$date" --ta "$artist" --tl "$album" --add-id3v2  - $output_dir/`basename $file`.mp3
done

echo "Conversions complete!"
